name: Generate Images JSON

on:
  push:
    paths:
      - 'assets/images/**'
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ensure images folder exists
        run: mkdir -p $GITHUB_WORKSPACE/assets/images

      - name: Generate images.json
        run: |
          # Get all image files in the folder (including subdirectories)
          FILES=$(find $GITHUB_WORKSPACE/assets/images -type f -regex ".*\.\(jpg\|jpeg\|png\)$")

          # Create the images.json file
          echo '{ "images": [' > $GITHUB_WORKSPACE/assets/images/images.json
          for file in $FILES; do
            echo "  \"${file}\"," >> $GITHUB_WORKSPACE/assets/images/images.json
          done
          sed -i '$ s/,$//' $GITHUB_WORKSPACE/assets/images/images.json
          echo '] }' >> $GITHUB_WORKSPACE/assets/images/images.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add $GITHUB_WORKSPACE/assets/images/images.json

          # Commit only if changes are present
          git diff --quiet || git commit -m "Update images.json"

          # Push changes
          git push || echo "No changes to push"
