name: Generate Images JSON

on:
  push:
    paths:
      - 'assets/images/**'
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ensure images folder exists
        run: mkdir -p assets/images

      - name: Generate images.json
        run: |
          # Get all image files in the folder, including HEIC (case-insensitive)
          FILES=$(ls assets/images | grep -Ei "\.(jpg|jpeg|png|heic)$" || true)

          # Create the images.json file
          echo '{ "images": [' > assets/images/images.json
          for file in $FILES; do
            echo "  \"${file}\"," >> assets/images/images.json
          done
          sed -i '$ s/,$//' assets/images/images.json
          echo '] }' >> assets/images/images.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add assets/images/images.json
          git commit -m "Update images.json" || echo "No changes to commit"
          git push || echo "No changes to push"
